### ISSUE TITLE
yank role commands

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/sir-lancebot#970]
## Description

Remove the subscribe commands from lance, because as of https://github.com/python-discord/bot/pull/1868, this is now supported on Bot. (Beautifully executed, too)

EDIT: Rather than removing the commands, they will be replaced with a message that tells the user to use the command on bot.

## Reasoning

No sense in having two commands that do the same thing, more maintenance work!

## Proposed Implementation

**TODO:**
- [x] remove lovefest role command
- [ ] remove advent of code command (deferred until January, when the command can no longer be assigned or removed)

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
To ease transition, I think it would be worth having the various commands send the user a message telling them to run `!subscribe` instead to get roles.

Probably worth updating Docstrings to reflect that too.

**Comment by onerandomusername** [comment]
That makes sense, I've updated the contents of the issue for that

**Comment by ChrisLovering** [comment]
Maybe have the messages delete_after ~20-30s too

**Comment by onerandomusername** [comment]
> Maybe have the messages delete_after ~20-30s too

I intentionally did not implement this, reasoning of not having stats on lance, so by leaving the responses, we can see if the commands are being used a lot, and not using the new commands.
